### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by milancurcic** [NOAA-EMC/fv3gfs#1]
Is FV3GFS released under any open source license or public domain?

**Comment by KateFriedman-NOAA** [comment]
Yes, we are using Apache License V2. License text is available at: 

https://github.com/NOAA-EMC/fv3gfs/blob/master/sorc/fv3gfs.fd/FV3_License_Public_Release_FY18Q2

**Comment by milancurcic** [comment]
Thank you, Kate!
